[platformio]
data_dir = spiffs_data
src_dir = src

[env:base]
platform = espressif32@^6.12.0
framework = espidf
board_build.sdkconfig_defaults = sdkconfig.defaults
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
build_flags = 
	-Iinclude
	-DLV_CONF_INCLUDE_SIMPLE

[env:esp32-s3-flaps]
extends = env:base
board = esp32-s3-devkitc-1
monitor_speed = 115200

board_build.flash_mode = dio
board_build.psram_type = opi
board_build.flash_size = 16MB
board_upload.flash_size = 16MB

build_unflags =
	-include

build_flags =
	${env:base.build_flags}
	-DTWAI_TX_GPIO=17
	-DTWAI_RX_GPIO=18
	-DBOARD_HAS_PSRAM
	-std=gnu++20
	-DCOMPONENTS=lvgl
	!echo "-DGIT_REVISION=\\\"$(git rev-parse --short=8 HEAD)\\\""
    ;-DENABLE_DIAGNOSTICS

extra_scripts =
	pre:support/patch_lvgl_adapter.py

[env:native]
platform = native
debug_extra_cmds =
	set args --no-splash --screen 2
lib_deps =
	https://github.com/DaveGamble/cJSON.git
lib_ldf_mode = off
build_src_filter =
	+<*>
	-<ble_ota.cpp>
	-<lvgl_src/**>
	+<lvgl_src/lv_init.c>
	+<lvgl_src/core/**>
	+<lvgl_src/display/**>
	+<lvgl_src/draw/*.c>
	+<lvgl_src/draw/convert/lv_draw_buf_convert.c>
	+<lvgl_src/draw/sdl/**>
	+<lvgl_src/draw/sw/**>
	+<lvgl_src/drivers/sdl/**>
	+<lvgl_src/font/**>
	+<lvgl_src/indev/**>
	+<lvgl_src/layouts/**>
	+<lvgl_src/libs/bin_decoder/**>
	+<lvgl_src/misc/**>
	+<lvgl_src/others/**>
	+<lvgl_src/osal/lv_os.c>
	+<lvgl_src/osal/lv_os_none.c>
	+<lvgl_src/stdlib/lv_mem.c>
	+<lvgl_src/stdlib/builtin/**>
	+<lvgl_src/themes/**>
	+<lvgl_src/tick/**>
	+<lvgl_src/widgets/**>
build_flags =
	-Iinclude
	-Imanaged_components/lvgl__lvgl
	-Imanaged_components/lvgl__lvgl/src
	-DLV_CONF_INCLUDE_SIMPLE
	-DNATIVE_TEST_BUILD
	-DNATIVE_SIMULATOR
	-DSDL_MAIN_HANDLED
	-std=gnu++20
	!pkg-config --cflags --libs sdl2
	!echo "-DGIT_REVISION=\\\"$(git rev-parse --short=8 HEAD)\\\""
